import { io } from 'socket.io-client';
const URL='http://localhost:3000'; const wait=(ms)=>new Promise(r=>setTimeout(r,ms));
let pass=0,fail=0; const ok=(c,m)=>(c?(pass++,console.log('  ✅',m)):(fail++,console.log('  ❌',m)));
const host=io(URL); await new Promise(r=>host.on('connect',r));
await host.emitWithAck('claim',{name:'인겸',clientId:'c-인겸'});
const p=io(URL); await new Promise(r=>p.on('connect',r)); await p.emitWithAck('claim',{name:'택윤',clientId:'c-택윤'});
let R=null; p.on('room:update',s=>R=s); let song=null; host.on('audio:song',s=>song=s);
const A=()=>R?.audio;
host.emit('host:endTournament'); await wait(120); host.emit('host:startTournament'); await wait(200);
host.emit('host:audio:start',{modeKey:'song1s'}); await wait(250);
ok(A()&&A().title===null,'1초노래 시작 + 제목 숨김(공개)');
ok(song&&typeof song.title==='string'&&'videoId' in song,'진행자만 곡 정보 수신(audio:song)');
ok(!('videoId' in A()),'공개 상태엔 videoId 없음(절대 비공개)');
host.emit('host:audio:reveal'); await wait(200);
ok(A().title===song.title,'정답 공개 → 제목 노출');
host.emit('host:audio:award',{team:'A'}); await wait(120);
host.emit('host:audio:award',{team:'A'}); await wait(120);
ok(A().score.A===2,`A 2점 (${A().idx}/${A().total})`);
host.emit('host:audio:finish'); await wait(200);
ok(A().winner==='A'&&R.tournament.teamScore.A===1,'결과 A승 + 승점');
host.emit('host:audio:end'); await wait(120);
// 랜덤플레이댄스: 제목 즉시 공개(hideTitle false)
host.emit('host:audio:start',{modeKey:'randomdance'}); await wait(250);
ok(A()&&A().title!==null,'랜플댄: 제목 즉시 공개(맞히는 게임 아님)');
host.emit('host:audio:end'); await wait(120);
// flow 레지스트리에 오디오 포함
host.emit('host:flow:start'); host.emit('host:flow:selector',{team:'A'}); await wait(250);
ok(R.flow.total>=22,`뽑기 레지스트리에 오디오 포함(총 ${R.flow.total}개)`);
host.emit('host:flow:end'); await wait(120);
console.log(`\n결과: ${pass} 통과 / ${fail} 실패`);
host.close(); p.close(); process.exit(fail?1:0);
